name: Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: |
          ./gradlew build